### ISSUE TITLE
[firestore-bigquery-export] support for array of objects(array of map) define a nested array schema 

### ISSUE THREAD

**Issue by Louna-akkad1** [firebase/extensions#1051] opened 2022-07-18 09:26 UTC
### [READ] Step 1: Are you in the right place?

Issues filed here should be about a feature request for a **specific extension in this repository**. To file a feature request that affects multiple extensions or the Firebase Extensions platform, please reach out to
[Firebase support](https://firebase.google.com/support/troubleshooter/report/features/) directly.

### [REQUIRED] Step 2: Extension name

firestore-bigquery-export

### What feature would you like to see?
i want to stream my collections in firestore to big query 
i was working by using scripts for generating schema views. However I when there is array of objects in Firestore document , it is not UNNESTing the object in array. Object appears as JSON values in view columns. How to UNNEST this ?

in my firestore document i have structure  where i have array of objects and there is no way to export to big query  with current firestore-bigquery-export 
check image

so we need schema type  to support array of objects

<img width="534" alt="Screen Shot 2022-07-18 at 1 22 17 PM" src="https://user-images.githubusercontent.com/89831789/179482085-56bbf9ae-9e1f-4de7-b8fc-3992a2193015.png">

### How would you use it?

i want to stream my collections in firestore to big query and be able to do queries on   array of objects inside document

**Comment by dackers86** [comment] 2022-07-19 15:17
Possibly related to https://github.com/firebase/extensions/issues/573

**Comment by yamankatby** [comment] 2022-09-28 13:15
Duplicate of #573

**Closed** 2023-11-23 11:00 UTC
Labels: type: feature request, extension: firestore-bigquery-export
