### ISSUE TITLE
[firestore-bigquery-change-tracker] Can't partition table on schema's `timestamp` column

### ISSUE THREAD

**Issue by bergold** [firebase/extensions#1023] opened 2022-06-24 18:44 UTC
### [READ] Step 1: Are you in the right place?

Yes

### [REQUIRED] Step 2: Describe your configuration

- Extension name: `firestore-bigquery-export`
- Extension version: `0.1.24`
- Configuration values (redacted all other values unrelated to partitioning):
  - `TABLE_PARTITIONING=MONTH`
  - `TIME_PARTITIONING_FIELD=timestamp`
  - `TIME_PARTITIONING_FIELD_TYPE=TIMESTAMP`
  - `TIME_PARTITIONING_FIRESTORE_FIELD` is left empty on purpose

> **Note**
> I want to use the `timestamp` column, which is already part of the BigQuery schema (and which contains the date and time of the function event). I don't want to extract some field from the Firestore document itself.

#### Steps to reproduce:

1. Deploy the extension with the above partitioning configuration.

##### Expected result

I expect the extension to create a partitioned table.

##### Actual result

The extensions creates a table without partitioning applied.

Here is the extension logs of the first invocation (which created the table):

<img width="1272" alt="Screenshot 2022-06-24 at 20 30 51" src="https://user-images.githubusercontent.com/6412650/175644274-dff88bb7-73f1-4f5b-a84f-f30efd31d59c.png">
 
(One thing to note: We had the extension already installed without partitioning enabled. I updated the extension and its configuration and deleted only the table (not the view) from BigQuery)

##### Hypothesis

I think the bug lays in the fact, that the `firestore-bigquery-change-tracker` either expects all or none of the custom partitioning options to be set. Even though I would expect it to also work with one of the other columns, that are already part of the schema (in my use case the `timestamp` column) and don't need to be extracted from the document data.

https://github.com/firebase/extensions/blob/f053443834d5ef4521100966d16367799e8340b8/firestore-bigquery-export/firestore-bigquery-change-tracker/src/bigquery/partitioning.ts#L93-L97

**Comment by dackers86** [comment] 2022-06-29 08:11
HI @bergold. There is also a scenario where we cannot partition an already existing table.

We are currently tracking this related issue https://github.com/firebase/extensions/issues/796 included are instructions on how to manually get around the issue

**Comment by bergold** [comment] 2022-06-29 13:02
However, this is not what I want to do. I want to use the `timestamp` column, which is already part of the BigQuery schema (and which contains the date and time of the function event).

I now, that it's nearly the same as using ingestion time partitioning with the pseudo column. However, because there is already the timestamp column and we are already using it for many of our queries, it would be nice if we could use that one. And, I thought that would also be supported based on the description of the config field, that I quoted in my last comment.

Thank you for your help and patience.

**Comment by yamankatby** [comment] 2022-09-29 09:44
Duplicate of #764

**Comment by dackers86** [comment] 2023-02-08 16:32
Hi @bergold.

Apologies for the delay on this feature. Having now added it our backlog for development, there doesn't seem to be an issue in using the `timestamp` field.

Did you experience any issues setting when trying to configure the timestamp field?

**Comment by bergold** [comment] 2023-02-09 09:35
I can confirm, that with the following configuration the table is still **not** partitioned:

```
BIGQUERY_PROJECT_ID=my-project-123
COLLECTION_PATH=users/{userid}/{collection}
DATASET_ID=firestore_export
DATASET_LOCATION=europe-west3
LOCATION=europe-west3
TABLE_ID=users
TABLE_PARTITIONING=MONTH
TIME_PARTITIONING_FIELD=timestamp
TIME_PARTITIONING_FIELD_TYPE=omit
USE_NEW_SNAPSHOT_QUERY_SYNTAX=yes
WILDCARD_IDS=true
```

**Comment by dackers86** [comment] 2023-02-10 08:52
The `TIME_PARTITIONING_FIELD_TYPE`  is a required field for adding partitioning. Have you tried setting this value to be `TIMESTAMP` to match the timestamp field value.

![image](https://user-images.githubusercontent.com/2060661/218046789-72821278-c690-4d30-81f9-413724c2fb81.png)

**Comment by bergold** [comment] 2023-02-11 13:23
Hi @dackers86,

Thank you for looking into this issue!

I tried that just now (uninstalled the extension, deleted the BigQuery dataset, reinstalled the extension), but it is still not partitioned.

I think, `TIME_PARTITIONING_FIRESTORE_FIELD` is also a required field for adding partitioning and this is the discrepancy of how it's currently working and what I'm trying to accomplish.

**Comment by dackers86** [comment] 2023-02-13 10:36
The Firebase console can be confusing with the `optional` fields. As we cannot have `conditional` parameters, we list them as optional.

However, for `partitioning`, the following fields are all required:

![image](https://user-images.githubusercontent.com/2060661/218435402-605d900c-690f-484d-8541-d61e272a3749.png)

The above configuration, should create a partitioned table based on the timestamp field, perhaps we need better documentation for this also?

**Comment by ca136** [comment] 2023-05-26 21:25
@dackers86 I have the same request as the OP, the config seems to be looking for a field in the Firestore doc called `timestamp`. By default, I would love it if the extension used the timestamp field created in the final BQ table for the partition.

Since this is a changelog, it makes more sense to partition by when each event occurs so we can batch-process the events. It can be a bit difficult to modify existing data flows, and even when I do have a date/time column I can use in the configuration it's not always in a format that the extension seems to accept.

**Closed** 2023-11-20 10:01 UTC
Labels: documentation, type: feature request, needs: author feedback, extension: firestore-bigquery-export

**Comment by iurisilvio** [comment] 2024-05-08 21:11
Using hour / timestamp / timestamp / TIMESTAMP in these for fields give me this error:

"Error caught creating table Field timestamp already exists in schema"

**Comment by iurisilvio** [comment] 2024-05-09 07:21
For future reference, hour / not set / not set / omit works for me. The partitions are created and it uses the timestamp field. I have a _PARTITIONTIME virtual column too.
