### ISSUE TITLE
[storage-resize-images] includePathList check not working when using firebase emulator on Windows

### ISSUE THREAD

**Issue by windmichael** [firebase/extensions#999] opened 2022-06-12 14:09 UTC
### Configuration

- Extension name: storage-resize-images
- Extension version: 0.1.28
- Configuration values (redact info where appropriate):
  -  "imageSizes": [ "400x600", "1500x3000" ],
  - "includePathList": [ "/images" ],
  - "deleteOriginalFile": 0,
  - "imageTypes": [ "webp" ],
  - "animated" : true

### Problem Description

The extension is not working, when using the firebase emulator on a Windows OS. 
The reason therefore are issues with the path separators. 

I detected two issues. 
For my use case, I configured the extension to only resize images in the "images" path. 
When uploading an image to the "images" folder, the extension checks, if the newly added images path is included in the "includePathList". But the path for the newly added images is "C:\\\images".
Thus, I get the following log message: "Image path 'C:\\\images' is not supported, these are the supported absolute paths: /images"

The reason therefore is the path separator in Node for Windows OS: [https://nodejs.org/docs/latest/api/path.html#pathsep](https://nodejs.org/docs/latest/api/path.html#pathsep)

A similar issue appears for uploading the image to the "images" folder again. 

#### Steps to reproduce:

Start the Firebase emulator with using this extension on a Windows OS. 

##### Expected result

Node uses as separator on Windows "\\\\". This should be replaces with "/" on the places where using the path.resolve method.

**Comment by dackers86** [comment] 2022-06-21 08:52
Thanks @windmichael. Added to our project board for investigation.

**Comment by juane1000** [comment] 2022-08-19 15:37
I've also just encountered this issue. Is there any update?

**Comment by remillc** [comment] 2023-09-12 14:25
I ran into the same issue. This is quite a bummer when developing with this extension under Windows. Please consider working on this issue.

**Comment by TheKents0209** [comment] 2023-11-14 20:32
Any workarounds?

**Comment by cabljac** [comment] 2023-11-16 10:49
For tracking purposes, closing this as a duplicate of https://github.com/firebase/extensions/issues/1732

**Closed by cabljac** 2023-11-16 10:49 UTC
Labels: type: bug, extension: storage-resize-images
