### ISSUE TITLE
Extension 'firebase/storage-resize-images' emulator, not working well with Windows

### ISSUE THREAD

**Issue by simenness** [firebase/extensions#1467] opened 2023-02-15 09:48 UTC
### Environment info
firebase-tools: ``11.23.1``

Platform: ``Windows 11``

### Configuration

``firebase.json``
```json
{
  "functions": [
    {
      "source": "functions",
      "codebase": "default",
      "ignore": [
        "node_modules",
        ".git",
        "firebase-debug.log",
        "firebase-debug.*.log"
      ],
      "predeploy": [
        "npm --prefix \"$RESOURCE_DIR\" run lint",
        "npm --prefix \"$RESOURCE_DIR\" run build"
      ]
    }
  ],
  "firestore": {
    "rules": "firestore.rules",
    "indexes": "firestore.indexes.json"
  },
  "storage": {
    "rules": "storage.rules"
  },
  "emulators": {
    "auth": {
      "port": 9099
    },
    "functions": {
      "port": 5001
    },
    "firestore": {
      "port": 8080
    },
    "storage": {
      "port": 9199
    },
    "ui": {
      "enabled": true
    },
    "singleProjectMode": true
  },
  "extensions": {
    "storage-resize-images": "firebase/storage-resize-images@0.1.34"
  }
}
```
``extensions\storage-resize-images.env``
```env
ALLOWED_EVENT_TYPES=firebase.extensions.storage-resize-images.v1.complete
DELETE_ORIGINAL_FILE=false
DO_BACKFILL=false
EVENTARC_CHANNEL=projects/${param:PROJECT_ID}/locations/europe-west4/channels/firebase
FUNCTION_MEMORY=2048
IMAGE_TYPE=jpeg,webp,png
IMG_BUCKET=demo
IMG_SIZES=500x500
IS_ANIMATED=true
LOCATION=europe-west1
MAKE_PUBLIC=true
RESIZED_IMAGES_PATH=thumbnails
```
#### Steps to reproduce:

Setup Firebase Emulator with config specified above with a demo project. (i use `--project demo-ember`)

Upload a JPEG to a {folder} in the Firebase Storage Emulator.

##### Expected result

Thumbnail gets generated/uploaded in a thumbnails/ folder next to the user uploaded file in {folder}.

##### Actual result

Thumbnail gets generated/uploaded to the root with {folder}\thumbnails\my_image.jpeg as the name``

### Related issues

https://github.com/firebase/extensions/issues/1732

**Comment by cabljac** [comment] 2023-05-25 08:41
I believe this should have been addressed by this [PR](https://github.com/firebase/extensions/pull/1416). 

Is this still occuring with the most recent version of the extension?

**Comment by mcavallo110** [comment] 2023-10-30 18:18
Still occurring to me

**Comment by TheKents0209** [comment] 2023-11-14 19:40
Still occurring to me too

**Comment by cabljac** [comment] 2023-11-16 10:26
Hey, appreciate this is still occurring and will look into this, I'm going to close this issue here as it's a duplicate of https://github.com/firebase/extensions/issues/1732 just for tracking purposes

**Closed by cabljac** 2023-11-16 10:26 UTC
Labels: type: bug, extension: storage-resize-images
