### ISSUE TITLE
[firestore-bigquery-export] Extension's cloud functions' location should be configurable

### ISSUE THREAD

**Issue by zubair-0** [firebase/extensions#1750] opened 2023-09-25 18:39 UTC
### [READ] Step 1: Are you in the right place?

Issues filed here should be about a feature request for a **specific extension in this repository**. To file a feature request that affects multiple extensions or the Firebase Extensions platform, please reach out to
[Firebase support](https://firebase.google.com/support/troubleshooter/report/features/) directly.

### [REQUIRED] Step 2: Extension name

This feature request is for extension: `firestore-bigquery-export`

### What feature would you like to see?

`firestore-bigquery-export` uses cloud functions as resources. Cloud functions' location itself is configurable as we can pass location parameter in [resources.properties.location](https://firebase.google.com/docs/extensions/reference/extension-yaml#1st-gen).
Right now, we are not passing this location in [extension.yaml](https://github.com/firebase/extensions/blob/next/firestore-bigquery-export/extension.yaml) so the location of cloud function resources default to `us-central1`.

In my case, bigquery instance is in a different region than the default region of cloud functions `us-central1` and ideally, I would like to deploy my cloud functions in the same region.

Extension should allow to the user to pass the cloud functions' location and then pass that location in resources.

### How would you use it?
I would specify the cloud function's location in extension's .env file. By doing this, the `DATASET_LOCATION` and `CLOUD_FUNCTION_LOCATION` would be same and it would make syncing faster.

**Comment by dackers86** [comment] 2023-09-30 07:45
HI @zubair-0.

Could you try using `LOCATION` as the parameters name?

**Comment by cabljac** [comment] 2023-09-30 08:35
Isn't this configurable in the advanced params now?

**Comment by zubair-0** [comment] 2023-10-02 04:18
> HI @zubair-0.
> 
> Could you try using `LOCATION` as the parameters name?

@dackers86 I already tried that as it was mentioned in the manifest documentation but it doesn't work.

**Comment by zubair-0** [comment] 2023-10-02 04:19
> Isn't this configurable in the advanced params now?

@cabljac can you please give a reference to code/docs? I'll read that and try it.

**Comment by JarnoRFB** [comment] 2023-10-02 20:43
Could it be that some error crept in, in version `0.1.33`? I get the error 

```Function location "fsexportbigquery" would be changed during update, which can have unexpected results. To change instance location, create a new instance instead.```

when trying to update from `0.1.32` to `0.1.33` via `firebase deploy --only extensions`. The extension instance has `DATASET_LOCATION=europe-west1` set in the `.env` file.

**Comment by KoheiKanagu** [comment] 2023-10-06 04:06
When installing an extension from the Firebase Console, you can choose the Cloud Functions Location, but when deploying with Firebase CLI, it defaults to us-central1.

<img width="538" alt="スクリーンショット 2023-10-06 12 52 03" src="https://github.com/firebase/extensions/assets/6175794/809cded5-064f-4084-adc0-356e8fbd92c5">

Even when using `firebase ext:export`, the Cloud Functions Location information is not output.

```yaml
BACKUP_COLLECTION=example
BIGQUERY_PROJECT_ID=${param:PROJECT_ID}
COLLECTION_PATH=example
DATASET_ID=firestore_export
DATASET_LOCATION=asia-northeast1
TABLE_ID=example
TABLE_PARTITIONING=NONE
TIME_PARTITIONING_FIELD_TYPE=omit
USE_NEW_SNAPSHOT_QUERY_SYNTAX=yes
WILDCARD_IDS=false
```

Comments that may possibly be relevant:
https://github.com/firebase/extensions/issues/1651#issuecomment-1745689011

**Comment by chrisspiegl** [comment] 2023-10-11 03:03
This issue is not limited to `firestore-bigquery-export`. It's the same for the `firestore-send-email` (and I am guessing others as well).

I also checked the `extension.yml` file and did not find any location parameter in there (which based on the docs I thought should be present as `immutable`).

Right now, it seems the only way to deploy the extensions to a specific region, is to do it through the web dashboard.

**Comment by dackers86** [comment] 2023-10-11 08:25
@chrisspiegl @KoheiKanagu @zubair-0 

Thanks for the updates on this, I've compiled and provided feedback on this feature/issue. 

I will update if I get anymore information.

@chrisspiegl Can you provide steps on how you currently configure through the web dashboard, it would help to get an idea of the difficulties users are facing

**Comment by dackers86** [comment] 2023-10-11 21:25
@chrisspiegl Can you confirm what version of the cli you are running for the above issues?

Could upgrading to the latest version be a potential fix?

**Comment by chrisspiegl** [comment] 2023-10-12 03:33
@dackers86 That was a great idea. There was an update for `firebase-tools` though it did not resolve the issue.

I uninstalled the `firestore-send-email` extension via the dashboard and then deployed it again via CLI from the above mentioned .env file. Again, all parameters are taken from the `.env` file but the  location is set to `us-central1`.

**Debug Info:**

```
System:
  OS: macOS 14.1
  CPU: (10) arm64 Apple M1 Max
  Memory: 23.17 GB / 64.00 GB
  Shell: 5.9 - /bin/zsh
Binaries:
  Node: 18.14.0 - ~/Library/pnpm/node
  npm: 9.3.1 - ~/Library/pnpm/npm
  pnpm: 8.7.4 - ~/Library/pnpm/pnpm
npmPackages:
  firebase: ^10.4.0 => 10.4.0
  firebase-tools: ^12.7.0 => 12.7.0
```

**Comment by marknesh** [comment] 2023-10-12 10:05
@dackers86 Could this be the reason why we can't reconfigure the cloud function location using the extension's `.env ` unless we uninstall the extension?

![Screenshot from 2023-10-12 12-37-48](https://github.com/firebase/extensions/assets/54584597/f3ed042b-7095-41d8-91f7-df518ea0b3fd)

**Comment by chrisspiegl** [comment] 2023-10-13 00:19
@marknesh how would this be done? Like this by setting the location in the extension `.env` file?

```
FIREBASEEXTENSIONS.V1BETA.FUNCTION/LOCATION=europe-west1

SMTP_CONNECTION_URI=smtp://xxxxxxxxxx@ethereal.email@smtp.ethereal.email:587
SMTP_PASSWORD=projects/${param:PROJECT_NUMBER}/secrets/firestore-send-email-SMTP_PASSWORD/versions/latest

DEFAULT_FROM=xxxx@xxxxx.com
DEFAULT_REPLY_TO=xxxx@xxxxx.com

MAIL_COLLECTION=Mail
TEMPLATES_COLLECTION=MailTemplate
USERS_COLLECTION=User

TTL_EXPIRE_TYPE=year
TTL_EXPIRE_VALUE=1
```

**Comment by KoheiKanagu** [comment] 2023-10-13 02:26
@chrisspiegl 
When I added the following to the `.env` file, I was able to change the location to asia-northeast1.
I tried it with both `firestore-send-email` and `firestore-bigquery-export`, and it worked for both.

```diff
BACKUP_COLLECTION=foo
BIGQUERY_PROJECT_ID=${param:PROJECT_ID}
COLLECTION_PATH=foo
DATASET_ID=firestore_export
DATASET_LOCATION=asia-northeast1
TABLE_ID=testResults_v1
TABLE_PARTITIONING=NONE
TIME_PARTITIONING_FIELD_TYPE=omit
USE_NEW_SNAPSHOT_QUERY_SYNTAX=yes
WILDCARD_IDS=false
+ firebaseextensions.v1beta.function/location=asia-northeast1
```


I think it's possible to specify the System parameters mentioned in this document as well: https://firebase.google.com/docs/extensions/publishers/parameters#system_parameters

**Comment by marknesh** [comment] 2023-10-13 06:53
> @marknesh how would this be done? Like this by setting the location in the extension `.env` file?
> 
> ```
> FIREBASEEXTENSIONS.V1BETA.FUNCTION/LOCATION=europe-west1
> 
> SMTP_CONNECTION_URI=smtp://xxxxxxxxxx@ethereal.email@smtp.ethereal.email:587
> SMTP_PASSWORD=projects/${param:PROJECT_NUMBER}/secrets/firestore-send-email-SMTP_PASSWORD/versions/latest
> 
> DEFAULT_FROM=xxxx@xxxxx.com
> DEFAULT_REPLY_TO=xxxx@xxxxx.com
> 
> MAIL_COLLECTION=Mail
> TEMPLATES_COLLECTION=MailTemplate
> USERS_COLLECTION=User
> 
> TTL_EXPIRE_TYPE=year
> TTL_EXPIRE_VALUE=1
> ```

```
firebaseextensions.v1beta.function/location=europe-west1
SMTP_CONNECTION_URI=smtp://xxxxxxxxxx@ethereal.email@smtp.ethereal.email:587
SMTP_PASSWORD=projects/${param:PROJECT_NUMBER}/secrets/firestore-send-email-SMTP_PASSWORD/versions/latest
DEFAULT_FROM=xxxx@xxxxx.com
DEFAULT_REPLY_TO=xxxx@xxxxx.com
MAIL_COLLECTION=Mail
TEMPLATES_COLLECTION=MailTemplate
USERS_COLLECTION=User
TTL_EXPIRE_TYPE=year
TTL_EXPIRE_VALUE=1
```

Use lowercase letters.

**Comment by chrisspiegl** [comment] 2023-10-13 08:17
I can confirm this now.

The location `.env` config parameter has to be lowercase letters.

Just in case, I also set the v2function parameter in my `.env` files for the `firestore-send-email` config files (in case they get updated sometime in the near(ish) future. And I kept the legacy `LOCATION` parameter (also, just in case).

```
LOCATION=europe-west1
firebaseextensions.v1beta.function/location=europe-west1
firebaseextensions.v1beta.v2function/location=europe-west1
```

Cheers for figuring this out together 🌸.

**Comment by dackers86** [comment] 2023-10-18 08:28
Hi All.

Thank you all for the input here, it seems we have a found a resolution. I'll close this issue for now.

A full summary has been written in a related issue [thread](https://github.com/firebase/extensions/issues/1651#issuecomment-1767943894)

**Closed by dackers86** 2023-10-18 08:28 UTC
Labels: type: feature request
