### ISSUE TITLE
🐛 [firestore-bigquery-export] Partitioning is not enabled when I specify "timestamp" as time partitioning column name.

### ISSUE THREAD

**Issue by RyosukeNishi** [firebase/extensions#1819] opened 2023-11-22 07:35 UTC
### [READ] Step 1: Are you in the right place?

Issues filed here should be about bugs for a **specific extension in this repository**.
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

- For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
  with the firebase tag.
- For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
  google group.
- To file a bug against the Firebase Extensions platform, or for an issue affecting multiple extensions, please reach out to
  [Firebase support](https://firebase.google.com/support/troubleshooter/contact/) directly.

### [REQUIRED] Step 2: Describe your configuration

- Extension name: **firestore-bigquery-export** (`storage-resize-images`, `firestore-send-email`, etc)
- Extension version: **0.1.37**
- Configuration values (redact info where appropriate):
<img width="644" alt="スクリーンショット 2023-11-22 16 20 59" src="https://github.com/firebase/extensions/assets/46443906/c77fc905-9bd5-4a39-b914-1614bc48917f">
<img width="647" alt="スクリーンショット 2023-11-22 16 21 08" src="https://github.com/firebase/extensions/assets/46443906/01b80d85-780d-4475-9102-c124ee0bc8ae">
<img width="642" alt="スクリーンショット 2023-11-22 16 21 21" src="https://github.com/firebase/extensions/assets/46443906/ca6dce3d-72e4-4538-a3ea-dd10ba4a4833">

#### Steps to reproduce:
- Install the extension with the configuration above.

What happened? How can we make the problem occur?
This could be a description, [log/console output](https://firebase.google.com/docs/extensions/manage-installed-extensions#view-logs), etc.

##### Expected result
Information about partitioning shows up on the table info pain on BigQuery console.

##### Actual result
It does not.
<img width="566" alt="スクリーンショット 2023-11-22 16 32 49" src="https://github.com/firebase/extensions/assets/46443906/c5bfb974-1654-4483-8f35-c03bec2bbccc">

**Comment by cabljac** [comment] 2023-11-23 15:26
You have "omit" as the partitioning type param in bigquery, I think this is meant to be set to TIMESTAMP for partitioning to be enabled. Does changing that parameter resolve the issue?

**Comment by RyosukeNishi** [comment] 2023-11-28 04:13
@cabljac 
Hi! May I know how long it might take for the PR to be merged?
I don't mean to haste you at all. I'd just like to know rough estimation in order to making a schedule for my work.
Thanks.

**Comment by cabljac** [comment] 2023-11-28 16:43
Hi @RyosukeNishi! Apologies, I previously thought this was a duplicate of a previous issue. I will look into your issue this week.

**Comment by cabljac** [comment] 2023-11-29 12:25
Hey, just to update you - I've reproduced this and will be implementing a fix. I will try to get a release out with it by the end of the week, or at worst Monday or Tuesday.

**Closed** 2023-12-01 10:40 UTC
Labels: type: bug, extension: firestore-bigquery-export

**Comment by RyosukeNishi** [comment] 2023-12-04 02:29
@cabljac 
The issue still exists. The code assumes that `timePartitioningFieldType` would be `undeifined` if only timestamp is specified, while the actual value is `omit`.

https://github.com/firebase/extensions/blob/b7fdbf91f3a64503e3e4de29e4fec3b0759bbf5c/firestore-bigquery-export/firestore-bigquery-change-tracker/src/bigquery/partitioning.ts#L98
<img width="505" alt="スクリーンショット 2023-12-04 11 20 50" src="https://github.com/firebase/extensions/assets/46443906/8f89e42e-46a3-4f5d-9a79-225bf039195b">

**Comment by quintisnel** [comment] 2024-02-11 06:51
@cabljac 
I still have the same issue with the extension on version 0.1.44. Created a new collection in firebase which have not been linked to a BigQuery export before. Created a new extension for this collection and specified the following:

![image](https://github.com/firebase/extensions/assets/15815798/c4b40b4f-f0dc-44e0-9539-09e599034b05)

In the logs the following is printed out: No valid table reference is available. Skipping partitioning. The xxx_latest table is created without partitioning, but the xxx_changelog table is created with partitioning. Is there a way to apply the partitioning to the _latest table in BigQuery?

**Comment by pr-Mais** [comment] 2024-02-12 14:12
@quintisnel could you please open a new issue to help track your problem?
