### ISSUE TITLE
@firebaseextensions/fs-bq-import-collection "Error importing Collection to BigQuery: Error: The default Firebase app already exists."

### ISSUE THREAD

**Issue by richbenwell** [firebase/extensions#1442] opened 2023-02-03 20:57 UTC
- Extension name: firestore-bigquery-export 
- Script: @firebaseextensions/fs-bq-import-collection
- Script version: 0.1.16

Running script version 0.1.16 (with default settings) outputs error:

`Error importing Collection to BigQuery: Error: The default Firebase app already exists. This means you called initializeApp() more than once without providing an app name as the second argument. In most cases you only need to call initializeApp() once. But if you do want to initialize multiple apps, pass a second argument to initializeApp() to give each app a unique name.`

Reverting to version 0.1.15, the script successfully imports rows without error.

**Comment by erlichmen** [comment] 2023-02-04 10:00
[Related](https://github.com/firebase/extensions/issues/978#issuecomment-1415717548)

**Comment by jimbobshocks** [comment] 2023-02-06 21:17
Same issue for me, running extension version:
firebase/firestore-bigquery-export@0.1.29
on a mac, with npx -v 8.5.5
Only affects view generation. Data sync continues as normal.

**Comment by francotc** [comment] 2023-02-07 21:10
Same problem here

**Comment by liberathor** [comment] 2023-02-11 09:34
same problem. There are my sample

input:
npx @firebaseextensions/fs-bq-import-collection --non-interactive --project=workky-pruebas --dataset=MasterDB --table-name-prefix=_ --source-collection-path=appUsersData --query-collection-group=false --dataset-location=us

output:
{"severity":"WARNING","message":"Warning, FIREBASE_CONFIG and GCLOUD_PROJECT environment variables are missing. Initializing firebase-admin will fail"}
Error importing Collection to BigQuery: Error: The default Firebase app already exists. This means you called initializeApp() more than once without providing an app name as the second argument. In most cases you only need to call initializeApp() once. But if you do want to initialize multiple apps, pass a second argument to initializeApp() to give each app a unique name.

**Comment by dackers86** [comment] 2023-02-13 11:37
Closing as a new release has been added. Please ping this issue occurs again.

https://github.com/firebase/extensions/pull/1455

**Closed by dackers86** 2023-02-13 11:37 UTC
Labels: type: bug

**Comment by asendia** [comment] 2023-02-14 04:53
`npx @firebaseextensions/fs-bq-import-collection` still produces the same error.

`npx @firebaseextensions/fs-bq-import-collection@0.1.15` works as @richbenwell mentioned.

**Comment by dackers86** [comment] 2023-02-14 08:57
Hi @asendia 

Can you provide a list of the cli options you have chosen for this error?

I cannot reproduce the error with the default configuration and wondering if a specific config is causing the problem.
