### ISSUE TITLE
[BUG] Image Resizing caught in infinite loop

### ISSUE THREAD

**Issue by danielfein** [firebase/extensions#29] opened 2019-10-08 04:16 UTC
### My issue:

- Extension name: **storageresize-images** 
- Configuration values (redact info where appropriate):
 - Defaults for all values except: sizes and cloud storage path
 - Sizes: `50x50,200x200,400x400,800x800`
 - Cloud Storage Path: `images`

### [REQUIRED] Step 3: Describe the problem

A few days ago I tried and the below occurred. I just tried again tonight and I'm facing the same issue, so figure this is the best place for this. I've just set the Resize Image extension up and the test run (just uploading an image) is causing an infinite loop of uploads and deletes (and error messages), where the newly resized images appear to be attempting to create new images, or something similar. My input for `Cloud Storage path for resized images` is `images` and this is leading to this error:

`Deleting temporary resized file: 'images/images/images/images/images/images/images/images/images/images/images/images/images/images/images/images/images/images/images/images/images/images/images/images/images/images/images/images/images/images/images/images/images/images/images/images/images/images/images/images/_200x200'`

I'm currently seeing an issue where a single image is causing the function to run until it hits:

Error when resizing image { Error: Backend Error
...
code: 503,
errors:
[ { domain: 'global',
reason: 'backendError',
message: 'Backend Error' } ],
response: undefined,
message: 'Backend Error' }

Any ideas for a solution to this? I uninstalled the extension to stop the infinite loop but not sure how to make the extension run smoothly.

The only steps I've taken so far were the setup guide of accepting a few things and changing the path to `images`.

#### Steps to reproduce:

What happened? How can we make the problem occur?

Configure extension for _images_ folder.
Upload image to _images_ folder.
Watch logs explode!

Here's an example of the logs:

```
12:10:59.174 AM
ext-storage-resize-images-generateResizedImage
Function execution took 18269 ms, finished with status: 'ok'
12:10:59.169 AM
ext-storage-resize-images-generateResizedImage
Deleted temporary original file: 'images/images/images/images/images/images/images/images/images/images/images/images/images/images/images/images/images/images/images/images/images/images/images/images/images/images/images/images/images/images/images/images/_50x50'
12:10:59.169 AM
ext-storage-resize-images-generateResizedImage
Deleting temporary original file: 'images/images/images/images/images/images/images/images/images/images/images/images/images/images/images/images/images/images/images/images/images/images/images/images/images/images/images/images/images/images/images/images/_50x50'
12:10:59.169 AM
ext-storage-resize-images-generateResizedImage
Failed execution of extension
12:10:59.169 AM
ext-storage-resize-images-generateResizedImage
Deleted temporary resized file: 'images/images/images/images/images/images/images/images/images/images/images/images/images/images/images/images/images/images/images/images/images/images/images/images/images/images/images/images/images/images/images/images/images/_50x50'
12:10:59.168 AM
ext-storage-resize-images-generateResizedImage
Deleting temporary resized file: 'images/images/images/images/images/images/images/images/images/images/images/images/images/images/images/images/images/images/images/images/images/images/images/images/images/images/images/images/images/images/images/images/images/_50x50'
12:10:59.168 AM
ext-storage-resize-images-generateResizedImage
Uploaded resized image to 'images/images/images/images/images/images/images/images/images/images/images/images/images/images/images/images/images/images/images/images/images/images/images/images/images/images/images/images/images/images/images/images/images/_50x50'
12:10:57.072 AM
ext-storage-resize-images-generateResizedImage
Function execution took 11315 ms, finished with status: 'ok'
12:10:57.058 AM
ext-storage-resize-images-generateResizedImage
Deleted temporary original file: 'images/images/images/images/images/images/images/images/images/images/images/images/images/images/images/images/images/images/images/images/images/images/images/images/images/images/images/images/images/images/images/images/images/images/images/images/images/_50x50'
12:10:57.058 AM
ext-storage-resize-images-generateResizedImage
Deleting temporary original file: 'images/images/images/images/images/images/images/images/images/images/images/images/images/images/images/images/images/images/images/images/images/images/images/images/images/images/images/images/images/images/images/images/images/images/images/images/images/_50x50'
12:10:57.058 AM
ext-storage-resize-images-generateResizedImage
Failed execution of extension
```

##### Expected result
Resized images at /images.

##### Actual result
Mayhem, as detailed above. I know the functionality is new, only let out into the wild 2 weeks ago! Definitely will be patient with it.*

**Comment by Salakar** [comment] 2019-10-08 09:08
Hey @danielfein 👋 thanks for the report. Looks like this is a duplicate of #7 so let's track this there. I have a PR ready to go to fix this which will be up soon.

Thanks

**Closed by Salakar** 2019-10-08 09:08 UTC

**Comment by danielfein** [comment] 2019-10-08 17:00
Thanks @Salakar!

**Comment by laurenzlong** [comment] 2019-10-11 21:08
@danielfein What is the name of the image you uploaded? And where did you upload it to? Was it  to the root of the bucket or a subfolder? (I'm trying to test the fix that's in flight)
