### ISSUE TITLE
queue - aborted no available instance

### ISSUE THREAD

**Issue by waste-app** [firebase/extensions#728] opened 2021-08-23 06:49 UTC
### [REQUIRED] Step 2: Describe your configuration

- Extension name: `firestore-send-email`
- Extension version: 0.1.10
- Configuration values (redact info where appropriate):
  - compliant

### [REQUIRED] Step 3: Describe the problem

![error](https://user-images.githubusercontent.com/58425391/130402695-b3f9651e-f89b-4263-a862-43fb91186c10.png)

queue - aborted no available instance

**Comment by dackers86** [comment] 2021-08-24 11:54
@waste-app Version `0.1.11` has been recently released. Does upgrading to this version fix the issue?

**Comment by jhuleatt** [comment] 2021-08-24 16:49
@waste-app per the [Cloud Functions docs](https://cloud.google.com/functions/docs/troubleshooting#:~:text=The%20request%20was%20aborted%20because%20there%20was%20no%20available%20instance), it looks like this may be caused by a Cloud Functions internal error. If you update to the latest version and are still experiencing this, please [reach out to Firebase support](https://firebase.google.com/support/troubleshooter/extensions/install).

**Comment by waste-app** [comment] 2021-08-29 07:55
![err1](https://user-images.githubusercontent.com/58425391/131243069-7e56ae2d-e447-47bc-acd8-f063aa4395e6.png)
![err2](https://user-images.githubusercontent.com/58425391/131243075-a80cca62-ff5c-4edc-9a76-b2c018bf4efa.png)

no

**Comment by waste-app** [comment] 2021-09-03 07:29
> @waste-app per the [Cloud Functions docs](https://cloud.google.com/functions/docs/troubleshooting#:~:text=The%20request%20was%20aborted%20because%20there%20was%20no%20available%20instance), it looks like this may be caused by a Cloud Functions internal error. If you update to the latest version and are still experiencing this, please [reach out to Firebase support](https://firebase.google.com/support/troubleshooter/extensions/install).

response:
...Now, issues or bugs in an existing extension are better attended on GitHub, for that you will need to create an issue in the Firebase Extensions GitHub. I know this is not the answer that you expected, but they are better prepared to help you with troubleshooting and also feature requests for existing extensions...

**Comment by NoizyCr1cket** [comment] 2021-09-03 15:09
> > @waste-app per the [Cloud Functions docs](https://cloud.google.com/functions/docs/troubleshooting#:~:text=The%20request%20was%20aborted%20because%20there%20was%20no%20available%20instance), it looks like this may be caused by a Cloud Functions internal error. If you update to the latest version and are still experiencing this, please [reach out to Firebase support](https://firebase.google.com/support/troubleshooter/extensions/install).
> 
> response:
> ...Now, issues or bugs in an existing extension are better attended on GitHub, for that you will need to create an issue in the Firebase Extensions GitHub. I know this is not the answer that you expected, but they are better prepared to help you with troubleshooting and also feature requests for existing extensions...
> 

I submitted a Firebase support ticket because I was seeing this error too with the distributed counter extension, and they gave me the same response.

**Comment by i14h** [comment] 2021-12-21 18:47
Thanks for the feedback everyone. Closing this as it's more of a runtime platform issue and nothing needs to be changed in the extensions atm.

**Closed by i14h** 2021-12-21 18:47 UTC
