### ISSUE TITLE
🐛 [Vector Search with Firestore] Error creating firestore Vector index. backfillTrigger() fail

### ISSUE THREAD

**Issue by karloti** [firebase/extensions#2102] opened 2024-05-22 14:27 UTC
The **backfillTrigger()** function fails if the specified text field to create the embed is **null**. 
In my case I can't set make text filed to be **empty** or any other text because it will create an incorrect **embedding** in the **vector database** with it. This text field is undergoing further processing, which may take several hours.

I would prefer that you handle fields that are **null** so that the function doesn't **fail**. 

Currently, for this reason, the installation process of this extension does not stop. 

I could change my field to blank to avoid the problem, but I think that should work for you. 

Thanks for advance and the email support.

**Comment by pr-Mais** [comment] 2024-05-23 09:50
Hello @karloti, can you open this issue in this repository https://github.com/GoogleCloudPlatform/firebase-extensions, as this extension is tracked there.

Moreover, could you provide your full configuration so we can attempt to re-produce the issue, thanks!

**Comment by karloti** [comment] 2024-05-23 10:17
> Hello @karloti, can you open this issue in this repository https://github.com/GoogleCloudPlatform/firebase-extensions, as this extension is tracked there.
> 
> Moreover, could you provide your full configuration so we can attempt to re-produce the issue, thanks!

I've already put in a lot of effort and I'm tired. I'm sorry I ran tests, wrote to support, opened a ticket, now you keep asking me to do things that I have already described many times I don't think it's appropriate In your case, just a specific function two problem in case the field value does not exist null. 
Please let someone do the support work instead of wasting our time. I spent 4 days on you and the error is trivial. In my case, this extension does not work and does not complete the installation successfully

**Comment by pr-Mais** [comment] 2024-05-23 10:28
@karloti I'm sorry to hear that, for all extensions it's always better to start by opening an issue in the extension's repo as this is the fastest way we can get informed and fix it.

Could you please just share a screenshot from your configuration (redact sensitive information) to ensure my setup matches yours, I'm already investigating it.

**Comment by pr-Mais** [comment] 2024-05-23 11:16
Hello @karloti, I couldn't re-produce, I had a field in my collection set to `null`, the extension completed processing all documents successfully. Here're my logs which shows the document being skipped as it's not valid. If you don't mind, could you provide more information (e.g. function logs, especially the function named `ext-firestore-vector-search-backfillTask`? is my steps to reproduce the same as yours?
![Screenshot 2024-05-23 at 2 11 30 PM](https://github.com/firebase/extensions/assets/41123719/0395229f-7030-453f-8aea-b2facb46241e)

**Comment by karloti** [comment] 2024-05-23 11:27
{
  "textPayload": "Unhandled error Error: Error creating firestore Vector
index\n    at /workspace/lib/index.js:79:15\n    at
process.processTicksAndRejections
(node:internal/process/task_queues:95:5)\n    at async
/workspace/node_modules/firebase-functions/lib/common/providers/tasks.js:74:17",
  "insertId": "664f25d4000281682fc905cd",
  "resource": {
    "type": "cloud_function",
    "labels": {
      "function_name": "ext-firestore-vector-search-backfillTrigger",
      "project_id": "znamtvserver",
      "region": "europe-west3"
    }
  },
  "timestamp": "2024-05-23T11:17:40.164200Z",
  "severity": "ERROR",
  "labels": {
    "execution_id": "q22ylpbe6uc5",
    "runtime_version": "nodejs18_20240513_18_20_2_RC00",
    "instance_id":
"00f46b9285082a9307c1a51ebc5bab86161696a3b7fe944a8919bdd28b1e00c0a8643e3c8996f20215bed1f2a9ddcd902ae65e72ee91efbd69ee568951d6ca2d002a"
  },
  "logName": "projects/znamtvserver/logs/cloudfunctions.googleapis.com
%2Fcloud-functions",
  "trace": "projects/znamtvserver/traces/f3ab9a2daa82437e76e385873bf760d0",
  "receiveTimestamp": "2024-05-23T11:17:40.200370295Z",
  "errorGroups": [
    {
      "id": "CNKtiY2AtN2-fQ"
    }
  ]
}

**Comment by pr-Mais** [comment] 2024-05-23 11:42
So the issue is not the field being null, but the creation of the index failing, which is a step before the backfill process starts. Is there any logs above the one you attached that states the reason why the index creation have failed?

**Comment by karloti** [comment] 2024-05-23 11:42
{
  "textPayload": "Error: 7 PERMISSION_DENIED: Permission denied on resource
project\n    at callErrorFromStatus
***@***.***/grpc-js/build/src/call.js:31:19)\n    at
Object.onReceiveStatus
***@***.***/grpc-js/build/src/client.js:192:76)\n    at
Object.onReceiveStatus
***@***.***/grpc-js/build/src/client-interceptors.js:360:141)\n
   at Object.onReceiveStatus
***@***.***/grpc-js/build/src/client-interceptors.js:323:181)\n
   at
***@***.***/grpc-js/build/src/resolving-call.js:99:78\n
 at process.processTicksAndRejections
(node:internal/process/task_queues:77:11)",
  "insertId": "664f25d400027f9128bb2a29",
  "resource": {
    "type": "cloud_function",
    "labels": {
      "project_id": "znamtvserver",
      "function_name": "ext-firestore-vector-search-backfillTrigger",
      "region": "europe-west3"
    }
  },
  "timestamp": "2024-05-23T11:17:40.163729Z",
  "severity": "ERROR",
  "labels": {
    "runtime_version": "nodejs18_20240513_18_20_2_RC00",
    "execution_id": "q22ylpbe6uc5",
    "instance_id":
"00f46b9285082a9307c1a51ebc5bab86161696a3b7fe944a8919bdd28b1e00c0a8643e3c8996f20215bed1f2a9ddcd902ae65e72ee91efbd69ee568951d6ca2d002a"
  },
  "logName": "projects/znamtvserver/logs/cloudfunctions.googleapis.com
%2Fcloud-functions",
  "trace": "projects/znamtvserver/traces/f3ab9a2daa82437e76e385873bf760d0",
  "receiveTimestamp": "2024-05-23T11:17:40.200370295Z",
  "errorGroups": [
    {
      "id": "CPTJ2fj3s5D8zwE"
    }
  ]
}

**Comment by karloti** [comment] 2024-05-23 11:56
[image: image.png]
I don't see what could be wrong in the settings.

**Comment by pr-Mais** [comment] 2024-05-23 11:58
The image isn't showing, can you upload it directly in a reply in the issue itself https://github.com/firebase/extensions/issues/2102.

**Comment by karloti** [comment] 2024-05-23 11:59
[image: image.png]

**Comment by pr-Mais** [comment] 2024-05-23 12:00
Sorry, I still see the image name only
![Screenshot 2024-05-23 at 2 59 56 PM](https://github.com/firebase/extensions/assets/41123719/16b0cf16-d11d-41f4-82c2-bb3aca21f8e6)

**Comment by karloti** [comment] 2024-05-23 12:04
![image](https://github.com/firebase/extensions/assets/6735500/3e91a337-014b-45f1-9162-65965a62ebe9)
![image](https://github.com/firebase/extensions/assets/6735500/0429dd24-80ec-424f-9eb8-c1db293fdf0a)

**Comment by cabljac** [comment] 2024-05-23 12:06
Are any of the resources deployed in a VPC by any chance? Trying to think where this permissions error is coming from

**Comment by karloti** [comment] 2024-05-23 12:08
My account is managed by Google Workspace

**Comment by karloti** [comment] 2024-05-23 12:13
![image](https://github.com/firebase/extensions/assets/6735500/9d743052-ae77-45db-8690-fbc6dea37c38)

**Comment by pr-Mais** [comment] 2024-05-23 12:25
every function in this extension will log the configuration values in every excution, so if you check the logs of any function you could see something like this (expand `jsonPayload` to see the config), could you check if `projectId` is set to your project ID?
![Screenshot 2024-05-23 at 3 23 44 PM](https://github.com/firebase/extensions/assets/41123719/27ae5f74-f7f6-4cbf-92c2-61b352cd8dcb)

**Comment by karloti** [comment] 2024-05-23 12:52
![image](https://github.com/firebase/extensions/assets/6735500/275042cb-4f65-44e7-954e-2b88eb05785b)

**Comment by karloti** [comment] 2024-05-23 12:55
![image](https://github.com/firebase/extensions/assets/6735500/e870242b-cea2-4e25-b03e-1d90528fd7fc)
This part with embedding work, but ... extension have problem with Vector Database

**Comment by pr-Mais** [comment] 2024-05-23 12:57
The search is failing cause there’s no index, which failed to create due to the permission error. We will be investigating this further.

**Comment by karloti** [comment] 2024-05-23 13:26
![image](https://github.com/firebase/extensions/assets/6735500/b8fc1840-9690-455e-bb65-db5a8489d1da)

**Comment by karloti** [comment] 2024-05-24 09:59
Problem solved.
I uninstalled the current extension and installed it on top of another collection for which all incoming embedding text fields are populated. The difference between the two collections is that in the first one that was failing, I had data that might have caused a serialization problem (timestamp), as well as data fields that were over 10k in Blob arrays. The embed input field in the first collection was not always initialized and had NULL values. In the second collection, there are unique records with fields that are not NULL, but are exactly the same as the first.
![image](https://github.com/firebase/extensions/assets/6735500/71c225d3-ff36-4584-bb2f-696264845d14)
![image](https://github.com/firebase/extensions/assets/6735500/6adc6da1-9bea-45d3-8a75-34b6ed15297e)
![image](https://github.com/firebase/extensions/assets/6735500/fb7a5c15-c681-48f2-b887-cf732930b6d9)
Although I could not test the function well in cloud console, but I will try to call it from Firebase Client SDK with service account.
The important thing is that the installation completed normally.
I still don't know how well this feature will do with Prefilters. I have arrays of strings in my collection that I want to filter. This can be difficult to realize. I don't want the function to return results that are not pre-filtered.

**Comment by cabljac** [comment] 2024-05-24 10:04
Hey, glad to hear it's working correctly with a fresh install. I'm still confused as I don't think the null/uninitialised values are what was causing the permissions error.

Did you try reinstalling the extension on the original collection? I'm thinking perhaps the roles for the extension service account weren't correctly applied

**Comment by karloti** [comment] 2024-05-24 10:12
I am about to test the function in the program and how to use it in RAG. If there is time, I will try it in the original collection, but I am limited by time.
I was currently using my account through the console. I'll check with the service guy. I might have missed something.
![image](https://github.com/firebase/extensions/assets/6735500/0d549813-2b5c-4535-be32-d21da7442c39)

**Comment by karloti** [comment] 2024-05-24 10:21
When serializing records from my collection, I get a warning that I'm not serializing the new two fields (embedding & status). What exactly is Vector<768>? 
FloatArray(768), .. DoubleArray(768)?
#Kotlin

**Comment by pr-Mais** [comment] 2024-05-24 10:24
@karloti sorry, I'm not really familiar with Kotlin. Vector is a type defined by Firestore clients, so I'm assuming the Kotlin client has it, check if you can import it as a type for your field instead of using built-in types.

**Comment by karloti** [comment] 2024-05-24 11:40
![image](https://github.com/firebase/extensions/assets/6735500/2e65a96b-e8e3-4159-ad98-b31cdcfb71a3)
![image](https://github.com/firebase/extensions/assets/6735500/115c6a5b-6107-4df4-9e96-17d350ef37bf)

**Comment by pr-Mais** [comment] 2024-05-24 11:47
@karloti can you confirm if this issue is resolved for you? if you encounter any other problems feel free to open a new issue here https://github.com/GoogleCloudPlatform/firebase-extensions

**Closed** 2024-05-24 11:54 UTC
Labels: type: bug
