### ISSUE TITLE
Resize Images - Firebase Storage Bucket Names Invalid

### ISSUE THREAD

**Issue by paulrenshaw-tls** [firebase/extensions#27] opened 2019-10-07 08:17 UTC
Expected behaviour:
Able to enter the name of firebase storage buckets in the extension configuration as they appear in the firebase console.

Actual behaviour:
'Invalid storage bucket' warning in extension configuration for names of storage buckets created in the firebase console. 'Install extension' button is not in a disabled state but does not respond in this scenario.

Further notes:
The firebase-admin sdk works perfectly well with storage names as they are entered when creating a new bucket in the console / displayed in the firebase console. It seems odd that you would restrict what can be entered in the extension configuration with validation rules different to whatever is used for creating buckets in the first place.

**Comment by rosariopfernandes** [comment] 2019-10-07 23:12
Sounds like a dupe of #18

**Comment by paulrenshaw-tls** [comment] 2019-10-08 07:40
> Sounds like a dupe of #18

#18 talks about defining a 'custom' bucket, implying something non-standard. The source for the extension has a regex filter for the bucket name requiring a string of text with a least 2 .s with strings around them i.e. 
```
 - param: IMG_BUCKET
    type: string
    label: Cloud Storage bucket for images
    description: >
      To which Cloud Storage bucket will you upload images that you want to resize?
      This bucket will store both the original and resized images.
    default: ${STORAGE_BUCKET}
    validationRegex: (.)+\.(.)+\.(.)+
    validationErrorMessage: Invalid storage bucket
    example: my-project-12345.appspot.com
    required: true
```
which is what is restricting entered values to something like the example value, but also allows anything else with 2 .s in, like a bucket URL such as in the example in the response by @Salakar or something like an IP address or even 'this.is.silly'

#18 talks about the issue that when you enter something incorrectly, it doesn't work. That's not an issue. Their expected result is 'It should use the defined bucket', but then they are giving an example not using a defined bucket and showing that that doesn't work - this doesn't demonstrate what the actual issue is, though it is a good demonstration of the wasted time it causes people to spend by not accepting valid entries.

It should not be expected that it uses whatever you define (since that might not be a bucket, as they demonstrate entering a value which is not a bucket), it should be expected that it accepts all and only valid bucket names, not just any value in the form [string].[string].[string]

My issue is that you can't enter something which would be correct.

P.S. Sorry I missed that issue, I think I dismissed it subconsciously because it is tagged as a bug and I didn't consider it a bug, as it seems very intentionally restricted to such values. If you could enter a bucket from the firebase storage console, and then it didn't work, that would be a bug in my eyes.

**Comment by laurenzlong** [comment] 2019-10-15 17:32
This is indeed a bug, since a valid storage bucket does not need to have any dots in it. For example, I can create a bucket called "my-bucket" on Cloud Console. That would be a valid bucket, but it would fail the regex validation. These are the guidelines for what a valid bucket name is: https://cloud.google.com/storage/docs/naming. It'll probably be too hard to have a regex to checks all of these conditions, nor would it be super helpful, since it still won't know whether the bucket in fact exists. I'm thinking that maybe the regex can simply check that the bucket name only contains valid characters (dots, dashes, underscores, letters, numbers). If the bucket doesn't actually exist, then the Extension will fail to install, and a detailed error message will show up which explains the bucket doesn't exist.

**Comment by mapkbalaji** [comment] 2019-12-29 23:47
Is there any progress to this bug? I couldn't choose a source from a different bucket. As of now, is there an option to choose a source from a directory from the default bucket?

**Comment by laurenzlong** [comment] 2019-12-30 18:45
@Ehesp @Salakar is this something you can make a pull request for? Thanks!

**Closed** 2020-01-21 10:17 UTC
Labels: blocked, type: bug
