### ISSUE TITLE
User delete data Error on permissions 

### ISSUE THREAD

**Issue by jimmykane** [firebase/extensions#371] opened 2020-06-30 07:53 UTC
### [READ] Step 1: Are you in the right place?

Issues filed here should be about bugs for a **specific extension in this repository**.
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

- For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
  with the firebase tag.
- For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
  google group.
- To file a bug against the Firebase Extensions platform, or for an issue affecting multiple extensions, please reach out to
  [Firebase support](https://firebase.google.com/support/troubleshooter/contact/) directly.

### [REQUIRED] Step 2: Describe your configuration

User-delete-data latest 

#### Steps to reproduce:

Not possible 

##### Expected result

Delete user data 

##### Actual result

```
Error when deleting: 'suuntoAppAccessTokens/n7uiTm8egsPZUuA7Rvc4ChBKGdY2' from Cloud Firestore { FirebaseError: Authorization failed. This account is missing the following required permissions on project [1mquantified-self-io[22m:
```

```
Error when deleting: 'suuntoAppAccessTokens/n7uiTm8egsPZUuA7Rvc4ChBKGdY2' from Cloud Firestore { FirebaseError: Authorization failed. This account is missing the following required permissions on project [1mquantified-self-io[22m:

  firebase.projects.get
    at Object.<anonymous> (/srv/node_modules/firebase-tools/lib/requirePermissions.js:41:19)
    at Generator.next (<anonymous>)
    at fulfilled (/srv/node_modules/firebase-tools/lib/requirePermissions.js:5:58)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:229:7)
  name: 'FirebaseError',
  children: [],
  context: undefined,
  exit: 1,
  message: 'Authorization failed. This account is missing the following required permissions on project \u001b[1mquantified-self-io\u001b[22m:\n\n  firebase.projects.get',
  original: undefined,
  status: 500 } 
```

**Comment by Ehesp** [comment] 2020-06-30 09:54
Hey @jimmykane it looks as though something hasn't installed properly when the extension was setup.

Could you try un-installing the extension and re-installing it again?

If that still causes issues, would you be able to check whether an [IAM & Service Account](https://console.cloud.google.com/iam-admin/iam?authuser=0&project=_&folder=) have been created correctly?

The names should look something like `ext-user-delete-data@project-name.iam.gserviceaccount.com`.

**Comment by jimmykane** [comment] 2020-06-30 11:31
Will do sir

**Comment by talas9** [comment] 2020-07-07 19:18
Same issue here, it seems like the project name has "1m" prefix, I'm not sure if this is just in the log or the extension is actually adding this to the project name

**Comment by jimmykane** [comment] 2020-07-17 14:51
Hi @Ehesp I reinstalled all is fine. 

The document the extension is trying to delete probably does not exist. 

Shouldn't that be a warning ? Did it work like this in the past because till I updated to the latest version I was not getting such errors but I might be wrong

**Comment by karayu** [comment] 2020-07-27 21:50
@russellwheatley do you mind taking a look?

**Comment by russellwheatley** [comment] 2020-07-30 14:35
The problem stems from missing permissions as noted in the error message: `'Authorization failed. This account is missing the following required permissions on project \u001b[1mquantified-self-io\u001b[22m:\n\n  firebase.projects.get'`

This type of error, from my experience, occurs when the IAM or service account permissions associated with the extension are accidentally deleted or invalidated somehow. Not something we have control over so I'm going to close this for now. Happy to open it again if I am mistaken and it is a reproducible bug.

**Comment by jimmykane** [comment] 2020-07-30 14:48
@russellwheatley  understandable but we only have installed the extension. 

We did an uninstall and reinstall but the issue remains still. 

That said the other document/collection deletes seem to work. 

So it fails in one collection with the above message.

**Comment by russellwheatley** [comment] 2020-07-30 15:05
My mistake, I assumed the extension was working again after reinstallation. Do you mind trying the following:
1. Delete any IAM & service account associated with this extension 
2. Uninstall the extension
3. Reinstall extension

Let me know how it goes, please. Thanks!

**Comment by jimmykane** [comment] 2020-07-30 15:24
Will do as soon as possible. Atm returning from a trip.

**Comment by Ehesp** [comment] 2020-08-25 12:15
Closing this due to inactivity. Please try the above steps and let us know - we'll reopen if the issue still occurs.

**Closed by Ehesp** 2020-08-25 12:15 UTC
Labels: type: bug
