### ISSUE TITLE
Add ability to replace original file, including name.

### ISSUE THREAD

**Issue by MrAndrew** [firebase/extensions#838] opened 2021-12-31 03:01 UTC
### [READ] Step 1: Are you in the right place?

Issues filed here should be about a feature request for a **specific extension in this repository**. To file a feature request that affects multiple extensions or the Firebase Extensions platform, please reach out to
[Firebase support](https://firebase.google.com/support/troubleshooter/report/features/) directly.

### [REQUIRED] Step 2: Extension name

This feature request is for extension: `storage-resize-images`

### What feature would you like to see?

I would like the ability to configure the function to simply replace the original file, including the file name so that the appending of the ratio isn't done so automatically. For example, `myPhoto.jpg` -> `myPhoto.webp` instead of `myPhoto_1080x1080.webp`. 

I see the modified file name on line 122 of resize-image.ts includes the file size by default. I'm sure this is due to the variable amount of file resizes the function can create, so modifying more than this line is necessary. 

### How would you use it?

I'd like to use this feature like I would normally use the extension function, just with an extra configuration option. For some use cases only one is desired or the original needs to be kept intact by name.

**Comment by dackers86** [comment] 2022-01-04 09:50
Duplicate of https://github.com/firebase/extensions/issues/653.

**Closed** 2023-06-13 15:21 UTC
Labels: type: feature request, extension: storage-resize-images
