### ISSUE TITLE
firestore-bigquery-export Collection path (single depth) regex error

### ISSUE THREAD

**Issue by nwparker** [firebase/extensions#437] opened 2020-08-21 21:29 UTC
### [READ] Step 1: Are you in the right place?

Issues filed here should be about bugs for a **specific extension in this repository**.
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

- For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
  with the firebase tag.
- For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
  google group.
- To file a bug against the Firebase Extensions platform, or for an issue affecting multiple extensions, please reach out to
  [Firebase support](https://firebase.google.com/support/troubleshooter/contact/) directly.

### [REQUIRED] Step 2: Describe your configuration

- Extension name: **\_** `firestore-bigquery-export`
- Extension version: **\_** `0.1.7`
- Configuration values (redact info where appropriate):
![image](https://user-images.githubusercontent.com/4138956/90936568-4b00fe80-e3ba-11ea-9cfe-cb9b74328804.png)

### [REQUIRED] Step 3: Describe the problem
I am trying to export the entire firestre collection named `events` to BigQuery, but upon saving the above configuration am faced with the following error: 

```
; RESOURCE_ERROR at /deployments/firebase-ext-firestore-bigquery-export/resources/fsexportbigquery: {"ResourceType":"gcp-types/cloudfunctions-v1:projects.locations.functions","ResourceErrorCode":"400","ResourceErrorMessage":{"code":400,"message":"The request has errors","status":"INVALID_ARGUMENT","details":[{"@type":"type.googleapis.com/google.rpc.BadRequest","fieldViolations":[{"field":"event_trigger","description":"Expected value /events/{documentId} to match regular expression [^/]+/[^/]+(/[^/]+/[^/]+)*"}]}],"statusMessage":"Bad Request","requestPath":"https://cloudfunctions.googleapis.com/v1/projects/lovecaster-f3c68/locations/us-central1/functions/ext-firestore-bigquery-export-fsexportbigquery","httpMethod":"PATCH"}}
```

---
Not sure if I'm doing something wrong or if #418 introduced this problem.

**Comment by CubitSpeed** [comment] 2020-08-24 20:16
+1
Also seeing this

**Comment by russellwheatley** [comment] 2020-08-25 12:40
Hey @nwparker, the regex from your error message `[^/]+/[^/]+(/[^/]+/[^/]+)*` is looking for an even amount of path segments (i.e. a document). The regex (`^[^/]+(/[^/]+/[^/]+)*$`) recently [merged](#418) is looking for an odd amount of path segments (i.e. a collection).

I think this error is coming from somewhere internally. We'll get this looked at either way, thanks for raising the issue!

**Comment by jhuleatt** [comment] 2020-08-25 16:47
@laurenzlong and @joehan it seems like CF3 is blocking this deploy, even though the params look ok to me. Any idea what might be going wrong?

**Comment by laurenzlong** [comment] 2020-08-25 17:36
Hi I wasn't able to reproduce this error with the same parameters. Did you previously have `/events` as the collection path? The leading slash can cause issues. 

![Screen Shot 2020-08-25 at 10 36 04 AM](https://user-images.githubusercontent.com/3990804/91208284-d205ed80-e6be-11ea-88d3-63768e576d83.png)

**Closed by laurenzlong** 2020-08-25 17:36 UTC
Labels: in-review, type: bug

**Comment by nwparker** [comment] 2020-08-25 21:49
> Hi I wasn't able to reproduce this error with the same parameters. Did you previously have `/events` as the collection path? The leading slash can cause issues.
> 
> ![Screen Shot 2020-08-25 at 10 36 04 AM](https://user-images.githubusercontent.com/3990804/91208284-d205ed80-e6be-11ea-88d3-63768e576d83.png)

Thanks @laurenzlong , removing and re-installing seems to have fixed things. However, shouldn't have re-configuring the extension have also worked? If so, should there be a bug opened for that issue?

**Comment by laurenzlong** [comment] 2020-08-26 18:39
Yes that is indeed a bug! Thanks for letting us know, I've filed an issue internally (bug ID 166473495) Since it's an issue with the platform not the extension itself, we don't track it in this repo.

**Comment by nwparker** [comment] 2020-08-26 21:20
> Yes that is indeed a bug! Thanks for letting us know, I've filed an issue internally (bug ID 166473495) Since it's an issue with the platform not the extension itself, we don't track it in this repo.

Thanks!
