### ISSUE TITLE
[BUG] Incorrect file name after resize

### ISSUE THREAD

**Issue by aravindvnair99** [firebase/extensions#135] opened 2019-12-14 16:21 UTC
### Configuration

- Extension name: `storage-resize-images`
- Extension version: `0.1.3`
- Configuration values (redact info where appropriate):
  - Deployment location: `us-central1`
  - Cloud Storage bucket for images: `\<projectID\>.appspot.com`
  - Sizes of resized images: `500x500`
  - Deletion of original file: `false`
  - Cloud Storage path for resized images: `thumbs`
  - Cache-Control header for resized images: Parameter not set

### Problem

After uploading an image, it is resized and named `_WIDTHxHEIGHT` without the original name.

#### Steps to reproduce:

Upload an image to storage bucket, let's say a.jpg

##### Expected result

`a_500x500.jpg` as the resized file name.

##### Actual result

`_500x500.jpg` as the resized file name.

**Comment by laurenzlong** [comment] 2019-12-17 19:30
Duplicate of https://github.com/firebase/extensions/issues/20

**Closed by laurenzlong** 2019-12-17 19:30 UTC
Labels: type: bug
