### ISSUE TITLE
Error with latest version of Big Query extension 0.1.33

### ISSUE THREAD

**Issue by madmacc** [firebase/extensions#1651] opened 2023-07-17 01:50 UTC
### [REQUIRED] Step 2: Describe your configuration

Stream Firestore to BigQuery
firebase/firestore-bigquery-export@0.1.33

#### Steps to reproduce:

Install the extension with the latest version and configure.
Add data to collections to sync with BQ.

##### Expected result
No errors and all data comes through to BQ.

##### Actual result
Errors and all data comes through to BQ.

`Error when mirroring data to BigQuery FirebaseFunctionsError: The principal (user or service account) lacks IAM permission "cloudtasks.tasks.create" for the resource "projects/hivepass-prod/locations/us-east1/queues/ext-firestore-bigquery-dynamic-links-syncBigQuery"`

![image](https://github.com/firebase/extensions/assets/43654472/f0137bed-5ee7-4f1f-9f37-a6a922ca0513)
```

Error when mirroring data to BigQuery FirebaseFunctionsError: The principal (user or service account) lacks IAM permission "cloudtasks.tasks.create" for the resource "projects/hivepass-prod/locations/us-east1/queues/ext-firestore-bigquery-dynamic-links-syncBigQuery" (or the resource may not exist).
    at FunctionsApiClient.toFirebaseError (/workspace/node_modules/firebase-admin/lib/functions/functions-api-client-internal.js:227:16)
    at /workspace/node_modules/firebase-admin/lib/functions/functions-api-client-internal.js:88:24
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /workspace/lib/index.js:106:9 {
  errorInfo: {
    code: 'functions/permission-denied',
    message: 'The principal (user or service account) lacks IAM permission "cloudtasks.tasks.create" for the resource "projects/hivepass-prod/locations/us-east1/queues/ext-firestore-bigquery-dynamic-links-syncBigQuery" (or the resource may not exist).'
  },
  codePrefix: 'functions'
}



```

**Comment by dackers86** [comment] 2023-07-17 10:42
Hi @madmacc 

Those permissions are granted automatically on the platform, looking at the resource it could potentially looking at the wrong location.

Can you navigate to `https://console.cloud.google.com/functions/details/us-central1/ext-firestore-bigquery-export-syncBigQuery?env=gen1&project=rc-release-testing` and confirm that your cloud functions for `syncBigQuery` exist in `us-east1`

**Comment by madmacc** [comment] 2023-07-17 21:35
Hi @dackers86,
Thanks for the quick response.
I get the following error with the link you sent. Note that I added authuser=3 to the params.

![image](https://github.com/firebase/extensions/assets/43654472/5d8956c0-cf7a-44c0-af2e-9825889cfac4)

Yes the queue seems to exist:
![image](https://github.com/firebase/extensions/assets/43654472/22e3eee4-91d2-470c-a8be-6fa40b20880d)

**Comment by madmacc** [comment] 2023-07-17 21:42
> Ah, my mistake. What about? https://console.cloud.google.com/functions/details/us-east1/ext-firestore-bigquery-dynamic-links-syncBigQuery?env=gen1&project=hivepass-prod

Same error

**Comment by madmacc** [comment] 2023-07-17 21:46
Got it at:
https://console.cloud.google.com/functions/details/us-central1/ext-firestore-bigquery-dynamic-links-syncBigQuery?env=gen1&project=hivepass-prod&authuser=3

**Comment by madmacc** [comment] 2023-07-17 21:48
![image](https://github.com/firebase/extensions/assets/43654472/87cd7089-6fa9-4b84-9f52-2f694d7a090c)

**Comment by dackers86** [comment] 2023-07-17 21:53
The problem line appears to be

```
         const queue = getFunctions().taskQueue(
           `locations/${config.location}/functions/syncBigQuery`,
           config.instanceId
         );
```

For the `fsexportbigquery` dynamic links function, what does the location say for in the `Details` tab?

**Comment by madmacc** [comment] 2023-07-17 21:57
us-central1
![image](https://github.com/firebase/extensions/assets/43654472/8ea3de2c-99d4-4775-a1b6-8a01c28a424b)

**Comment by dackers86** [comment] 2023-07-17 21:59
Oops, sorry the `variables`. This is where the configuration is stored for a Firebase Extension.

**Comment by madmacc** [comment] 2023-07-17 22:01
> Oops, sorry the `variables`. This is where the configuration is stored for a Firebase Extension.

![image](https://github.com/firebase/extensions/assets/43654472/581cc969-86cf-46bd-955f-499e77a52669)

**Comment by madmacc** [comment] 2023-07-17 22:03
I'm guessing this is something to do with the extensions running on uscentral-1 and all my other resources being on us-east1?

**Comment by dackers86** [comment] 2023-07-17 22:14
Yes, I think so. to summarise so far:

1. The call is correctly looking for your function at `us-east1` based on the config location.
2. The deployment has installed the extension at `us-central1`, the same location as the original install.
3. The error is ultimately saying it cannot find the resource, permissions is a red herring in that error message.

I'm curious how the location has changed, as this field is `immutable`. Do you know if any of these updates been applied through the `firebase-tools` cli?

**Comment by madmacc** [comment] 2023-07-17 22:23
> 

I did all of the extension installation and updates via the Firebase web console. console.firebase.google.com.
I just looked again and noticed that the ones that are having the errors are the ones that where already in existance and were updated to the latest version (v0.1.33) from v0.1.30. e.g. collection "dynamicLinks"
The new one I installed for collection "adminUsers" seems to have no errors and is working fine.

Images for adminUsers extension function
![image](https://github.com/firebase/extensions/assets/43654472/72982ba4-2a4e-4485-8737-fc35c0e2cd4d)

![image](https://github.com/firebase/extensions/assets/43654472/c068315c-7d74-401f-8df0-c0e9986a052c)

**Comment by dackers86** [comment] 2023-07-17 22:48
Ok, thanks. We can try to replicate this scenario to see if I can find a solution. 

Installing a new instance, could potentially be a solution in the meantime?

**Comment by madmacc** [comment] 2023-07-17 23:08
I just tried that. 
Uninstalling and installing the extension again fixes the problem.
Lucky I just tested on non critical collections first.
I will wait for a solution before moving my high transaction and critical collections to v0.1.33 as the down time may cause issues.

**Comment by dackers86** [comment] 2023-07-24 14:53
I've been investigating this further, but no luck yet. Steps taken so far:

1. Install the previous version on `us-central1`.
2. Update the `functions/region` / `compute/region` to my closest region `europe/west2`.
3. Update the extension
4. The function successfully installs in the `us-central1` region.

**Comment by luckyhandler** [comment] 2023-07-25 07:15
I have a similar problem and after the last update my `Cloud Functions location` suddenly changed from Frankfurt Germany to Iowa. This is an irreversible operation and cannot be manually changed from my side any more. I guess that the right problems arise from this fact.

<img width="725" alt="image" src="https://github.com/firebase/extensions/assets/8419137/6da7c165-7d50-4d59-84cb-1b82ed13ed41">

**Comment by lmesz** [comment] 2023-08-07 11:08
We faced the exact same problem, our original extension was installed to EU.
@dackers86 These steps might help you to reproduce.
1. You need an old version of extension e.g.: 0.1.24 if I am not mistake this was our old version.
2. Install it to EU multiregion and function location to europe-west1
3. Upgrade the extension without modifying any data.
4. Your function should be in europe-west1 but it will be in us-central1, and the problem is that, it wants to use a task queue in europe-west1 but the queue is in us-central1 so it can't use it.

The only solution (I didn't try much) that worked for me is the reinstall of the extension.

**Comment by dackers86** [comment] 2023-08-08 21:44
Hi All.

Just an update on this, the problem is not to do with the extension, it is instead a platform issue. 

The Firebase team are currently investigating!

**Comment by darnmason** [comment] 2023-08-11 05:25
While upgrading the extension I noticed that the configuration form displayed us-central1 in the immutable region field but I figured it was just a bug in the form, but nope now my resources have all moved to the us-central1 region.

**Comment by honestzack** [comment] 2023-08-15 23:51
Hi, in my case the issue is that the migration to the new version sets DATASET_LOCATION = US
<img width="377" alt="Screenshot 2023-08-15 at 7 49 40 PM" src="https://github.com/firebase/extensions/assets/116735829/27e99827-241d-4c6f-a4de-01aa230628b6">

**Comment by luckyhandler** [comment] 2023-09-20 05:42
> Hi All.
> 
> Just an update on this, the problem is not to do with the extension, it is instead a platform issue.
> 
> The Firebase team are currently investigating!

Is this solved? Where can I get the current state of this. I don't update my extensions right now to prevent this from happening again after I recreated all of them.

**Comment by pavelgj** [comment] 2023-10-03 20:38
Sorry for the delayed reply, there were multiple reports related to the same underlying root-cause and looks like I missed this issue. The fix for this issue was deployed on August 25. The resetting of location to `us-central1` during update should not be happening anymore, it should preserve the old value. If you notice any more issues related to this please let us know.

**Comment by dackers86** [comment] 2023-10-18 08:26
Hi All.

Based on the response from Pavel. Plus the related issues, here is a full summer:

### Deployment issues

An platform update was provided in August for fixing the functions deploying to the wrong locations, when upgrading an extension.

### Configuration options 

Location is now no longer a configurable option within an extensions configuration, although niche cases such as where to deploy assets (BQ dataset location for example) could be added to an extensions configurable parameters.

Location is configurable through the followijg two options:

 - CLI: Update to the latest version and you should be able configure the location through your `.env` file

```
LOCATION=europe-west1
firebaseextensions.v1beta.function/location=europe-west1
firebaseextensions.v1beta.v2function/location=europe-west1
```

- Web interface

![image](https://github.com/firebase/extensions/assets/2060661/d542cbcc-d900-47c7-957b-23cc0dd77f69)


Overall it is now safe to upgrade to the latest versions, and for any configuration please follow the above steps!

Closing this issue for now. Happy to re-open if any more issues are encountered.

**Closed by dackers86** 2023-10-18 08:26 UTC
Labels: type: bug, needs: author feedback

**Comment by dylanrandle** [comment] 2023-12-29 01:03
FWIW, I encountered the same/similar issue for the Algolia search extension. Uninstall/reinstall fixed it for me as well.
