### ISSUE TITLE
Delete User Data extension doesnt fire after using deleteUsers function

### ISSUE THREAD

**Issue by CalvinJamesHeath** [firebase/extensions#1549] opened 2023-05-08 23:24 UTC
### [REQUIRED] Step 2: Describe your configuration

- Extension name: **\_** (`Delete User Data`,)
- Extension version: **\_**(`firebase/delete-user-data@0.1.16`)

### [REQUIRED] Step 3: Describe the problem
My experience is the same with Delete User Data. also following deployment. It doesn't fire when I delete a user using a function; it only fires when I directly delete a user in Firebase Authentication.
#### Steps to reproduce:
Install the extension
Set extension configuration with firestorePath/{UID} and save.

What happened? How can we make the problem occur? THE PROBLEM 🥁
if I add all the userIds in an array, loop them and call:

```
admin
				.auth()
				.deleteUser(uid)
```
The Delete User Data extension gets called and it all works fine. However if we do:

```
admin
				.auth()
				.deleteUsers(unVerifiedUsers)
```
While passing and array of user UID's or an individial UID string, it still deletes the users in Firebase Authentication but the extension doesnt get called. 

##### Expected result
For the extension to fire after deleting a firebase auth user via a function.

##### Actual result
The extension works only when I manually delete a Firebase auth user in the Firebase authentication console.

**Comment by cabljac** [comment] 2023-06-12 16:11
Hey there, just reproduced this and am looking into it.

**Comment by cabljac** [comment] 2023-06-12 16:19
It seems `admin.auth.deleteUsers()` will not trigger auth events by design. I think the idea is that `deleteUsers` is meant for bulk deletion, and anything you want to perform after bulk deletion you should do manually within the application logic. See the discussion here for example:

https://github.com/firebase/firebase-functions/issues/860

I will bring this up with the team, but it might be that this blocks us.

**Comment by CalvinJamesHeath** [comment] 2023-06-16 12:45
Thank you, for conclusion for anybody else reading, batch operations like auth().deleteUsers() don't trigger async functions.

**Comment by cabljac** [comment] 2023-06-16 16:32
closing this for now, as i don't think this is something we can change, at least in this repo. Thanks!

**Closed by cabljac** 2023-06-16 16:32 UTC
Labels: type: bug, blocked, extension: delete-user-data
