### ISSUE TITLE
Gen Schema View should allow for inputing a location

### ISSUE THREAD

**Issue by flauc** [firebase/extensions#523] opened 2020-12-03 09:32 UTC
### [REQUIRED] Step 2: Describe your configuration

- Extension name: `firestore-bigquery-export`
- Extension version: `0.1.10`

### [REQUIRED] Step 3: Describe the problem

The `gen-schema-view` script needs to have the option to pass in a location. At the moment if the bigquery database is created in any other location then "US" the script won't work.

#### Steps to reproduce:

Connecte the firebase extension and specifcy any location other then "US" for bigquery.

##### Expected result

The script allowes `--location=EU` to be added when runing it. 

##### Actual result

This prevents the execution of the script.

**Comment by russellwheatley** [comment] 2020-12-03 11:04
Hi Flauc, thanks for raising the issue. Could you paste the error message you received here, please? I have tested creating views from a table with a dataset in "europe-west2" previously as mentioned in this [issue](https://github.com/firebase/extensions/issues/512). Sounds like there might be something going on, but it's hard to debug if I cannot reproduce.

**Comment by flauc** [comment] 2020-12-03 11:22
I'm actually referring to the location of the bigquery instance. The error you get when including `--location` the script is just rejected since that isn't registered as an argument. If you omit it though the bigquery location defaults to "US" and the view fails to create saying there is no datatable with the provided name.

**Comment by russellwheatley** [comment] 2020-12-03 12:08
I've just created a dataset in `EU`, added data, and created a view with no problem using the `gen-schema-view` script.

I suspect you might not have created the changelog table within the dataset which is why it cannot find it. Have you added any data to the Firestore collection you specified when creating the BigQuery extension (presuming you have created one)?

The other possibility might be the collection name you're using as an input for `tableNamePrefix`. You have to specify the same collection name as you used for creating the BigQuery extension.

**Comment by russellwheatley** [comment] 2020-12-15 16:40
I'm going to close this, I will reopen if there is a reproducible bug in the `firestore-bigquery-export` extension.

**Closed by russellwheatley** 2020-12-15 16:40 UTC
