### ISSUE TITLE
Cannot delete a extension

### ISSUE THREAD

**Issue by choipd** [firebase/extensions#395] opened 2020-07-23 01:17 UTC
### [REQUIRED] Step 2: Describe your configuration

- Extension name: `firestore-bigquery-export`
- Extension version: `0.1.6`

#### Steps to reproduce:

When I delete the extension, I got error so I can not delete it.

What happened? How can we make the problem occur?
`
; RESOURCE_ERROR at /deployments/firebase-ext-firestore-bigquery-export-45jd/resources/fsexportbigquery: {"ResourceType":"gcp-types/cloudfunctions-v1:projects.locations.functions","ResourceErrorCode":"400","ResourceErrorMessage":{"code":400,"message":"Invalid function service account requested: ext-firestore-bigquery-ex-bkk9@xxxxxxxxxxx.iam.gserviceaccount.com","status":"INVALID_ARGUMENT","statusMessage":"Bad Request","requestPath":"https://cloudfunctions.googleapis.com/v1/projects/xxxxxxxxxxx/locations/asia-northeast1/functions","httpMethod":"POST"}}
`

##### Expected result
I can delete the extension without error.

##### Actual result
RESOURCE_ERROR

**Comment by russellwheatley** [comment] 2020-07-23 10:03
Hey, @choipd, you don't appear to be the only user having some difficulty uninstalling your extension. I have made a comment [here](https://github.com/firebase/extensions/issues/393#issuecomment-662921005) on how you might overcome this problem at this moment in time. Could you let me know if this solves your problem, please?

**Comment by laurenzlong** [comment] 2020-07-23 17:47
Sorry you're having this issue! I'm going to close this as a duplicate of https://github.com/firebase/extensions/issues/393 so we can keep the conversation in there.

**Closed by laurenzlong** 2020-07-23 17:47 UTC
