### ISSUE TITLE
🐛 [firestore-translate-text] Error on updating Extension 

### ISSUE THREAD

**Issue by amin79** [firebase/extensions#2108] opened 2024-05-31 11:20 UTC
### [REQUIRED] Step 2: Describe your configuration

- Extension name: **\_** (firestore-translate-text)
- Extension version: **\_** firebase/firestore-translate-text@0.1.16
- Configuration values (redact info where appropriate):
  - **\_**
  - **\_**

### [REQUIRED] Step 3: I have these target languages: en,de,ar,ru,fr,es,tr,fa
When I try to update the extension and add one more language, when I click on save, I get the exception: There was an unknown error while processing the request.

<img width="956" alt="Screenshot 2024-05-31 at 13 15 52" src="https://github.com/firebase/extensions/assets/33101184/4586f26a-4f4d-40a3-a66f-9dee14b6b1b4">

#### Steps to reproduce:

Just try to reconfigure an extension and add a new language.

What happened? How can we make the problem occur?
This could be a description, [log/console output](https://firebase.google.com/docs/extensions/manage-installed-extensions#view-logs), etc.

**Comment by Gustolandia** [comment] 2024-11-27 23:25
Hi. I have followed every single information given here. The version where this bug occurred was ## Version 0.1.16. We are currently in ## Version 0.1.19. I cannot reproduce the error in the current version (I can add new languages without any issue (I have added all the languages stated and more), so I am assuming this issue was fixed by one of the 3 updates done to the extension. I am closing the issue. Please submit a new issue if in the latest version of the extension it continues. Thank you.

**Closed by Gustolandia** 2024-11-27 23:25 UTC
Labels: type: bug, extension: firestore-translate-text
