### ISSUE TITLE
fsexportbigquery function does not deploy

### ISSUE THREAD

**Issue by keatonwalker** [firebase/extensions#529] opened 2020-12-10 04:59 UTC
### [READ] Step 1: Are you in the right place?

Issues filed here should be about bugs for a **specific extension in this repository**.
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

- For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
  with the firebase tag.
- For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
  google group.
- To file a bug against the Firebase Extensions platform, or for an issue affecting multiple extensions, please reach out to
  [Firebase support](https://firebase.google.com/support/troubleshooter/contact/) directly.

### [REQUIRED] Step 2: Describe your configuration

- Extension name: firestore-bigquery-export
- Extension version: v0.1.10
- Configuration values (redact info where appropriate):
  - Cloud Functions location Description
    - us-central1
  - BigQuery Dataset location Description
    - us
  - Collection path Description
    - testposts
  - Dataset ID Description
    - firestore_export_test
  - Table ID Description
    - posts_test

### [REQUIRED] Step 3: Describe the problem
The fsexportbigquery function does not deploy

The extension give the following error in the firebase console:
> ; RESOURCE_ERROR at /deployments/firebase-ext-firestore-bigquery-export/resources/fsexportbigquery: {"ResourceType":"gcp-types/cloudfunctions-v1:projects.locations.functions","ResourceErrorCode":"400","ResourceErrorMessage":"Failed to retrieve function source code"}

The error in Cloud Functions is:
> Invalid argument (HTTP 400): Failed to retrieve function source code

The source location Deployment Manager sets for the Cloud Function deployment  manager appears not to exist:
gs://firebase-mod-sources-prod/609537b69c8912a0d69067bed55781a4d998262350f44d0db8ce1c48470105ed

#### Steps to reproduce:

1) Create a new Firebase project
2) Enable billing and the Blaze Plan
3) Attempt to install the firestore-bigquery-export extension

##### Expected result
The extension should fully deploy into my project

##### Actual result
The Cloud Function that was a component of the extension did not deploy.

**Comment by dimavedenyapin** [comment] 2020-12-10 10:41
I am experiencing the same issue.
I can't update my existing extensions from 0.1.9 to 0.1.10 or create a new one

**Comment by russellwheatley** [comment] 2020-12-10 10:44
Hey @jhuleatt & @i14h, I can confirm this is a bug that will need further investigation.

**Comment by joaoaguiam** [comment] 2020-12-10 11:48
I also confirm this is not working, if you retry it seems to be installed correctly, however, nothing is added on the BigQuery.

Is there a way to use an older version?

**Comment by tinaliang** [comment] 2020-12-10 19:46
Hey all,

Sorry you've been having the issues. Install should be working via the CLI now. We're working on fixing installs through the Console and will post another update when it's been rolled out. In the meantime, please use the CLI for all installs/udpates.

**Comment by yilunc** [comment] 2020-12-11 15:20
Hi @tinaliang, is there another bug related to deploying from the CLI? I just tried deployment through it and am seeing this error in Firebase console for my new deployment:

```
; RESOURCE_ERROR at /deployments/firebase-ext-organizations-labels/resources/fsexportbigquery: {"ResourceType":"gcp-types/cloudfunctions-v1:projects.locations.functions","ResourceErrorCode":"500","ResourceErrorMessage":"Failed to configure trigger providers/cloud.firestore/eventTypes/document.write@firestore.googleapis.com (__gcf__.us-central1.ext-organizations-labels-fsexportbigquery)"}
```

**Comment by tinaliang** [comment] 2020-12-14 20:02
Console installs and updates should now be fixed as well.

Closing this bug as everything should be working normally now.

**Closed by tinaliang** 2020-12-14 20:02 UTC
Labels: type: bug
