### ISSUE TITLE
[firestore-send-email] Cannot read property 'sendMail' of undefined on an invalid smtp url

### ISSUE THREAD

**Issue by dackers86** [firebase/extensions#1472] opened 2023-02-20 08:48 UTC
### [REQUIRED] Step 2: Describe your configuration

- Extension name: firestore-send-email
- Extension version: 0.1.23
- Configuration values (redact info where appropriate):
  - smtpUri  - smtps://${email}:smtp.gmail.com:465

#### Steps to reproduce:

1. Add an email address that has `smtps://${email}:smtp.gmail.com:465` instead of `smtps://${email}@smtp.gmail.com:465`.
2. Send an Email
3. You will receive the error

##### Expected result

Email should send successfully

##### Actual result

Receive the error "Cannot read property 'sendMail' of undefined"

##### Additional notes

This line https://github.com/firebase/extensions/blob/0696bfe518b318c4530700f348a4a97bd7c55942/firestore-send-email/functions/src/index.ts#L274 should have a check to see if the url was validated successfully. If not, warn the error and potentially add an error to the document that the smtp url is invalid.

**Comment by TetrixGauss** [comment] 2023-11-21 19:05
any updates on this?

**Comment by TetrixGauss** [comment] 2023-11-22 12:05
@pr-Mais do you know when it is going to be merged?

**Comment by pr-Mais** [comment] 2023-11-22 17:18
@TetrixGauss I believe this PR #1817 isn't directly related to your issue, as it seems your SMTP URI is in the correct format, did you try removing the password from the URI and putting it in the **SMTP password** field instead?

**Comment by TetrixGauss** [comment] 2023-11-23 18:08
@pr-Mais hey! I just don't that and now the error changed to "`Hostname/IP does not match certificate’s altnames: Host: conciefy.com. is not in the cert’s altnames: DNS:ukpro5.fcomet.com` .

Any suggestions?

**Comment by pr-Mais** [comment] 2023-11-24 09:53
It's possible that the issue is with your provider. One possible way to go over it is mentioned here https://github.com/nodemailer/nodemailer/issues/342#issuecomment-56969235, we will soon release a new version that allows you to configure TLS options https://github.com/firebase/extensions/pull/1788

**Closed** 2023-11-24 14:36 UTC
Labels: type: bug, extension: firestore-send-email
